# Generated by Django 4.1.7 on 2023-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_alter_content_data_alter_content_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
